###
GET http://localhost:5232

###
POST http://localhost:5232/funcionalidade

###
GET  http://localhost:5232/api/produto/listar

### Cadastrar Produto
POST   http://localhost:5232/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "MousePad",
}